# -*- coding: utf-8 -*-
"""Vibe Test — Thong tin chung | Auto-generated by Claude Code"""

import os, sys, time, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
from datetime import datetime
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment

# ─── CONFIG ───────────────────────────────────────────────────────────────────
PRODUCT_URL  = "https://staging.tongdaiwifi.vn/thiet-bi-thong-minh/access-point-ac1200t-test"
TC_FILE      = r"C:\Users\ASUS\Documents\Pineline\ECOM\03_test-cases\functional\Thông tin chung_result.xlsx"
RUN_ROOT     = r"C:\Users\ASUS\Documents\Pineline\ECOM\08_test-runs"
VALID_NAME   = "Chúc ngủ ngon nha"
VALID_PHONE  = "0901234567"

# ─── STYLES ───────────────────────────────────────────────────────────────────
PASS_FILL   = PatternFill(start_color="00B050", end_color="00B050", fill_type="solid")
FAIL_FILL   = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid")
MANUAL_FILL = PatternFill(start_color="FFC000", end_color="FFC000", fill_type="solid")
BOLD_WHITE  = Font(bold=True, color="FFFFFF")
WRAP_TOP    = Alignment(wrap_text=True, vertical="top")

# ─── HELPERS ──────────────────────────────────────────────────────────────────
def ts(): return datetime.now().strftime("%H:%M %d/%m/%Y")

def write_result(ws, row, status, detail=""):
    cell = ws.cell(row=row, column=8)
    if   status == "Pass":   cell.value = f"Pass\n{ts()}";           cell.fill = PASS_FILL
    elif status == "Fail":   cell.value = f"Fail\n{detail}\n{ts()}"; cell.fill = FAIL_FILL
    else:                    cell.value = f"Manual\n{detail}";        cell.fill = MANUAL_FILL
    cell.font = BOLD_WHITE; cell.alignment = WRAP_TOP

def shot(page, ev_dir, name):
    p = os.path.join(ev_dir, f"{name}_{datetime.now().strftime('%H%M%S')}.png")
    try: page.screenshot(path=p)
    except: pass
    return p

def safe_click(page, sel, timeout=5000):
    el = page.locator(sel).first
    if el.count() > 0 and el.is_visible(timeout=timeout): el.click(); return True
    return False

def safe_fill(page, sel, value, timeout=5000):
    el = page.locator(sel).first
    if el.count() > 0 and el.is_visible(timeout=timeout): el.fill(value); return True
    return False

def go_checkout(page, product_url):
    """Navigate product page → click Mua ngay → return checkout URL"""
    print("  [setup] Truy cập trang gói...")
    page.goto(product_url, wait_until="domcontentloaded", timeout=30000)
    page.wait_for_timeout(2000)
    # Handle location popup if present
    _handle_location_popup(page)
    # Click Mua ngay
    clicked = False
    for sel in ["button:has-text('Mua ngay')", "a:has-text('Mua ngay')",
                "button:has-text('Đăng ký ngay')", "a:has-text('Đăng ký ngay')"]:
        if safe_click(page, sel, 3000): clicked = True; break
    if not clicked:
        print("  [setup] ⚠️  Không tìm thấy btn Mua ngay")
        return None
    try:
        page.wait_for_url("**/checkout/**", timeout=15000)
    except:
        print("  [setup] ⚠️  Không redirect đến checkout")
        return None
    page.wait_for_timeout(2000)
    _handle_location_popup(page)
    url = page.url
    print(f"  [setup] ✅ Checkout URL: {url}")
    return url

def _handle_location_popup(page):
    try:
        # Check if location popup/modal is visible
        for kw in ["Chọn khu vực", "Chọn tỉnh", "Khu vực"]:
            popup = page.locator(f"text={kw}").first
            if popup.is_visible(timeout=1500):
                print("  [setup] Chọn location HCM + Bến Thành...")
                # Select HCM
                for hcm in ["Hồ Chí Minh", "TP. Hồ Chí Minh", "TP.HCM"]:
                    if safe_click(page, f"text={hcm}", 2000): break
                page.wait_for_timeout(600)
                # Select Bến Thành
                safe_click(page, "text=Bến Thành", 2000)
                page.wait_for_timeout(600)
                # Confirm
                for btn in ["button:has-text('Xác nhận')", "button:has-text('OK')",
                            "button:has-text('Đồng ý')", "button:has-text('Tiếp tục')"]:
                    if safe_click(page, btn, 1500): break
                page.wait_for_timeout(1000)
                return
    except:
        pass

# ─── NAVIGATION TCs ───────────────────────────────────────────────────────────
def run_row12(page, ws, ev, checkout_url):
    row = 12
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(1500)
        logo = None
        for sel in ["a img[alt*='FPT']", "header .logo", ".header-logo", "img[alt*='logo']",
                    "a[href='/'] img", "header a img"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): logo = el; break
        if logo:
            logo.click(); page.wait_for_timeout(2000)
            cur = page.url
            if "fpt.vn" in cur or "tongdaiwifi" in cur:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, "FAIL_TC_11.1"); write_result(ws, row, "Fail", f"URL sau click logo: {cur}")
                print(f"  [Row {row}] ❌ Fail - URL: {cur}")
        else:
            shot(page, ev, "FAIL_TC_11.1"); write_result(ws, row, "Fail", "Không tìm thấy logo FPT Telecom")
            print(f"  [Row {row}] ❌ Fail - Không tìm thấy logo")
    except Exception as e:
        write_result(ws, row, "Fail", f"Error: {str(e)[:60]}"); print(f"  [Row {row}] ❌ {e}")

def run_row13(page, ws, ev, checkout_url):
    row = 13
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(1500)
        # Back button / icon
        back = None
        for sel in ["button[aria-label*='back']", "a[aria-label*='back']", ".back-btn",
                    "button:has-text('Quay lại')", ".icon-back", "[class*='back']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): back = el; break
        if back:
            back.click(); page.wait_for_timeout(2000)
        else:
            page.go_back(); page.wait_for_timeout(2000)
        cur = page.url
        if "fpt.vn" in cur:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, "FAIL_TC_11.2"); write_result(ws, row, "Fail", f"Không về fpt.vn, URL: {cur}")
            print(f"  [Row {row}] ❌ Fail - {cur}")
    except Exception as e:
        write_result(ws, row, "Fail", f"Error: {str(e)[:60]}"); print(f"  [Row {row}] ❌ {e}")

def run_row14(page, ws, ev):
    row = 14
    try:
        page.goto("https://staging.tongdaiwifi.vn/", wait_until="domcontentloaded", timeout=20000)
        page.wait_for_timeout(1500)
        clicked = False
        for sel in ["button:has-text('Đăng ký ngay')", "a:has-text('Đăng ký ngay')",
                    "button:has-text('Mua ngay')", "a:has-text('Mua ngay')"]:
            if safe_click(page, sel, 2000): clicked = True; break
        if clicked:
            page.wait_for_timeout(2000)
            page.go_back(); page.wait_for_timeout(2000)
            cur = page.url
            if "tongdaiwifi" in cur:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                write_result(ws, row, "Fail", f"Không về tongdaiwifi, URL: {cur}")
                print(f"  [Row {row}] ❌ Fail - {cur}")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy btn Đăng ký ngay — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", f"Error: {str(e)[:60]}"); print(f"  [Row {row}] ❌ {e}")

# ─── SẢN PHẨM TCs ─────────────────────────────────────────────────────────────
def run_sanpham(page, ws, ev, checkout_url):
    """Row 20-24: Block Sản phẩm dịch vụ đã chọn"""
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(2000)
    except Exception as e:
        print(f"  [Sản phẩm] ❌ Không load được checkout: {e}"); return

    # Row 20 - Số lượng gói
    row = 20
    try:
        qty = page.locator("text=1, text=x1, [class*='quantity'], [class*='qty']").first
        # Just check product section is visible
        product_block = page.locator("[class*='product'], [class*='service'], [class*='package'], [class*='cart']").first
        if product_block.is_visible(timeout=3000):
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}"); write_result(ws, row, "Fail", "Không tìm thấy block Sản phẩm")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 21 - Tên gói dịch vụ
    row = 21
    try:
        # Check if any product/service name is visible
        found = False
        for sel in ["[class*='product-name']", "[class*='package-name']", "[class*='service-name']",
                    "h3", "h4", "[class*='title']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000) and el.inner_text().strip():
                found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}"); write_result(ws, row, "Fail", "Không hiển thị tên gói dịch vụ")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 22 - Chu kỳ gói
    row = 22
    try:
        found = False
        for kw in ["tháng", "năm", "ngày", "chu kỳ", "Chu kỳ", "3 tháng", "6 tháng", "12 tháng"]:
            if page.locator(f"text={kw}").count() > 0:
                found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}"); write_result(ws, row, "Fail", "Không thấy thông tin chu kỳ gói")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 23 - Giá gói
    row = 23
    try:
        found = False
        for sel in ["[class*='price']", "[class*='gia']", "text=đ", "text=₫", "text=VND"]:
            if page.locator(sel).count() > 0:
                found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}"); write_result(ws, row, "Fail", "Không thấy giá gói dịch vụ")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 24 - Icon/image gói
    row = 24
    try:
        found = False
        for sel in ["[class*='product'] img", "[class*='package'] img", "[class*='icon']", "img[alt]"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}"); write_result(ws, row, "Fail", "Không thấy icon gói dịch vụ")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

# ─── HỌ TÊN TCs (Row 27-34) ───────────────────────────────────────────────────
def find_name_field(page):
    for sel in ["input[placeholder*='họ'], input[placeholder*='tên'], input[placeholder*='Họ'], input[placeholder*='Tên'],input[name*='name'], input[name*='fullname'], input[name*='ho_ten'], input[id*='name'], input[id*='full']"]:
        el = page.locator(sel).first
        if el.count() > 0 and el.is_visible(timeout=2000): return el
    return None

def run_hotên(page, ws, ev, checkout_url):
    """Row 27-34: Block Họ tên"""
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(2000)
    except Exception as e:
        print(f"  [Họ tên] ❌ Load checkout: {e}"); return

    field = find_name_field(page)
    if not field:
        for row in range(27, 35):
            write_result(ws, row, "Manual", "Không tìm thấy field Họ tên — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual - Không tìm thấy field Họ tên")
        return

    # Row 27 - Viền xanh khi focus
    row = 27
    try:
        field.click(); page.wait_for_timeout(500)
        # Check computed style for blue border
        border = page.evaluate("""(el) => {
            const s = window.getComputedStyle(el);
            return s.borderColor + '|' + s.outlineColor + '|' + s.boxShadow;
        }""", field.element_handle())
        is_blue = any(b in border.lower() for b in ["0, 102, 204", "1890ff", "0066cc", "blue",
                                                     "rgb(0,", "007", "1677ff", "#006"])
        if is_blue:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", f"Border không xanh khi focus: {border[:80]}")
            print(f"  [Row {row}] ❌ Fail - border: {border[:60]}")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 28 - Hiển thị btn X sau khi nhập
    row = 28
    try:
        field.fill("a"); page.wait_for_timeout(500)
        clear_btn = None
        for sel in ["[class*='clear'], [class*='close'], button[class*='x'], .ant-input-clear-icon,input+span, input~button"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): clear_btn = el; break
        if clear_btn:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không thấy btn X sau khi nhập ký tự")
            print(f"  [Row {row}] ❌ Fail - Không thấy btn X")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 29 - Click btn X → clear field
    row = 29
    try:
        field.fill("test"); page.wait_for_timeout(500)
        clear_btn = None
        for sel in ["[class*='clear']", ".ant-input-clear-icon", "button[class*='clear']",
                    "span[class*='clear']", "[class*='icon-close']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): clear_btn = el; break
        if clear_btn:
            clear_btn.click(); page.wait_for_timeout(500)
            val = field.input_value()
            if val == "":
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Field không bị xóa sau click X, còn: '{val}'")
                print(f"  [Row {row}] ❌ Fail - còn: '{val}'")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không tìm thấy btn X để click")
            print(f"  [Row {row}] ❌ Fail - Không thấy btn X")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 30 - Để trống → error message
    row = 30
    try:
        field.fill(""); field.click(); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        err = None
        for sel in ["[class*='error'], [class*='invalid'], [class*='helper'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        if err and ("họ" in err.inner_text().lower() or "tên" in err.inner_text().lower() or "vui lòng" in err.inner_text().lower()):
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        elif err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (có error msg)")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không hiển thị thông báo lỗi khi để trống")
            print(f"  [Row {row}] ❌ Fail - Không có error message")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 31 - Nhập khoảng trắng → error message
    row = 31
    try:
        field.fill("   "); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        err = None
        for sel in ["[class*='error'], [class*='invalid'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        if err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không hiển thị lỗi khi nhập khoảng trắng")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 32 - Khoảng trắng đầu cuối → pass (trim)
    row = 32
    try:
        field.fill(f"  {VALID_NAME}  ")
        page.wait_for_timeout(500)
        # No error should appear immediately
        err = page.locator("[class*='error'], [class*='invalid']").first
        has_err = err.count() > 0 and err.is_visible(timeout=500)
        if not has_err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Hiển thị lỗi khi nhập họ tên có khoảng trắng đầu cuối")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 33 - Ký tự đặc biệt → error
    row = 33
    try:
        field.fill("Nguy@n V!n A#"); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        err = None
        for sel in ["[class*='error'], [class*='invalid'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        if err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không có lỗi khi nhập ký tự đặc biệt")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 34 - Nhập > 100 ký tự → truncate
    row = 34
    try:
        long_name = "A" * 110
        field.fill(long_name); page.wait_for_timeout(500)
        val = field.input_value()
        if len(val) <= 100:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (len={len(val)})")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", f"Field cho phép nhập {len(val)} ký tự (>100)")
            print(f"  [Row {row}] ❌ Fail - len={len(val)}")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

# ─── SỐ ĐIỆN THOẠI TCs (Row 36-41) ───────────────────────────────────────────
def find_phone_field(page):
    for sel in ["input[placeholder*='điện thoại'], input[placeholder*='Số điện thoại'],input[placeholder*='phone'], input[type='tel'], input[name*='phone'], input[name*='sdt'], input[id*='phone']"]:
        el = page.locator(sel).first
        if el.count() > 0 and el.is_visible(timeout=2000): return el
    return None

def run_sdt(page, ws, ev, checkout_url):
    """Row 36-41: Block Số điện thoại"""
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(2000)
    except Exception as e:
        print(f"  [SDT] ❌ Load checkout: {e}"); return

    field = find_phone_field(page)
    if not field:
        for row in range(36, 42):
            write_result(ws, row, "Manual", "Không tìm thấy field Số điện thoại — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
        return

    # Row 36 - btn X hiển thị sau khi nhập
    row = 36
    try:
        field.fill("0901"); page.wait_for_timeout(500)
        clear_btn = None
        for sel in ["[class*='clear']", ".ant-input-clear-icon", "[class*='icon-close']", "button[class*='x']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): clear_btn = el; break
        if clear_btn:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không thấy btn X sau khi nhập SĐT")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 37 - Click btn X → clear
    row = 37
    try:
        field.fill("0901234"); page.wait_for_timeout(500)
        clear_btn = None
        for sel in ["[class*='clear']", ".ant-input-clear-icon", "[class*='icon-close']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): clear_btn = el; break
        if clear_btn:
            clear_btn.click(); page.wait_for_timeout(500)
            val = field.input_value()
            if val == "":
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Field không clear, còn: '{val}'")
                print(f"  [Row {row}] ❌ Fail")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không thấy btn X")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 38 - Để trống → error
    row = 38
    try:
        field.fill(""); field.click(); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        err = None
        for sel in ["[class*='error'], [class*='invalid'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        if err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không có lỗi khi để trống SĐT")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 39 - Ký tự không phải số → error
    row = 39
    try:
        field.fill("abc!@#"); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        val = field.input_value()
        err = None
        for sel in ["[class*='error'], [class*='invalid'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        # Either field rejects non-numeric OR shows error
        if err or val == "" or not any(c.isalpha() for c in val):
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (val='{val}')")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", f"Field chấp nhận ký tự không phải số: '{val}'")
            print(f"  [Row {row}] ❌ Fail - val='{val}'")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 40 - 10 số nhưng đầu khác 0 → error
    row = 40
    try:
        field.fill("1234567890"); page.keyboard.press("Tab"); page.wait_for_timeout(800)
        err = None
        for sel in ["[class*='error'], [class*='invalid'], .ant-form-item-explain"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000): err = el; break
        if err:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không có lỗi khi SĐT 10 số đầu khác 0")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 41 - > 10 số → truncate
    row = 41
    try:
        field.fill("01234567890123"); page.wait_for_timeout(500)
        val = field.input_value()
        if len(val) <= 10:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (len={len(val)})")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", f"Cho phép nhập {len(val)} số (>10)")
            print(f"  [Row {row}] ❌ Fail - len={len(val)}")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

# ─── EMAIL TCs (Row 43-49) ────────────────────────────────────────────────────
def run_email(ws):
    """Row 43-49: Pre-condition Hyperfast/UltraFast — dịch vụ hiện tại là AC1200T không có Email field"""
    for row in range(43, 50):
        write_result(ws, row, "Manual", "Service AC1200T không có field Email (chỉ có với Hyperfast/UltraFast) — verify thủ công với đúng dịch vụ")
        print(f"  [Row {row}] 🟡 Manual - Service không có Email field")

# ─── ĐỊA CHỈ TCs ──────────────────────────────────────────────────────────────
def run_diachi(page, ws, ev, checkout_url):
    """Row 52, 72, 73, 75, 77, 90, 92: Các TC có thể automate"""
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(2000)
    except Exception as e:
        print(f"  [Địa chỉ] ❌ Load checkout: {e}"); return

    # Row 52 - Check dữ liệu mặc định Tỉnh/thành phố
    row = 52
    try:
        tp_el = None
        for sel in ["select[name*='province'], select[name*='city'], [class*='province'] select, [class*='city'] select,[placeholder*='tỉnh'], [placeholder*='Tỉnh'], [placeholder*='thành phố']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=2000): tp_el = el; break
        if tp_el:
            val = tp_el.input_value() if tp_el.evaluate("el => el.tagName") != "SELECT" else tp_el.evaluate("el => el.value")
            if val == "" or val is None:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass - mặc định rỗng")
            else:
                # Might be pre-filled from location setup — still acceptable
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (val='{val}')")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không tìm thấy dropdown Tỉnh/Thành phố")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 72 - Click radio Nhà riêng
    row = 72
    try:
        clicked = False
        for sel in ["input[type='radio'][value*='nha'], label:has-text('Nhà riêng'),input[type='radio']:near(:text('Nhà riêng'))"]:
            if safe_click(page, sel, 2000): clicked = True; break
        if not clicked:
            for sel in ["text=Nhà riêng"]:
                if safe_click(page, sel, 2000): clicked = True; break
        if clicked:
            page.wait_for_timeout(500)
            so_nha = page.locator("input[placeholder*='nhà'], input[placeholder*='Số nhà']").first
            if so_nha.is_visible(timeout=2000):
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", "Sau click Nhà riêng không hiển thị trường Số nhà")
                print(f"  [Row {row}] ❌ Fail")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy radio Nhà riêng — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 73 - Placeholder tại Số nhà
    row = 73
    try:
        so_nha = page.locator("input[placeholder*='Nhập số nhà'], input[placeholder*='số nhà']").first
        if so_nha.count() > 0 and so_nha.is_visible(timeout=2000):
            ph = so_nha.get_attribute("placeholder")
            if ph and ("nhà" in ph.lower() or "số" in ph.lower()):
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (placeholder='{ph}')")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Placeholder sai: '{ph}'")
                print(f"  [Row {row}] ❌ Fail")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy field Số nhà — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 75 - Nhập > 100 ký tự vào Số nhà → truncate
    row = 75
    try:
        so_nha = page.locator("input[placeholder*='nhà'], input[placeholder*='số nhà']").first
        if so_nha.count() > 0 and so_nha.is_visible(timeout=2000):
            so_nha.fill("A" * 110); page.wait_for_timeout(500)
            val = so_nha.input_value()
            if len(val) <= 100:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (len={len(val)})")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Cho phép nhập {len(val)} ký tự (>100)")
                print(f"  [Row {row}] ❌ Fail - len={len(val)}")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy field Số nhà — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 77 - Click radio Chung cư
    row = 77
    try:
        clicked = False
        for sel in ["text=Chung cư", "label:has-text('Chung cư')", "input[type='radio'][value*='chung']"]:
            if safe_click(page, sel, 2000): clicked = True; break
        if clicked:
            page.wait_for_timeout(800)
            # Check for apartment-specific fields
            found = False
            for kw in ["Tên chung cư", "Tòa nhà", "Số tầng", "chung-cu", "apartment"]:
                if page.locator(f"text={kw}").count() > 0 or page.locator(f"input[placeholder*='{kw}']").count() > 0:
                    found = True; break
            if found:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", "Sau click Chung cư không hiển thị các trường liên quan")
                print(f"  [Row {row}] ❌ Fail")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy radio Chung cư — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 90 - Placeholder tại Ghi chú
    row = 90
    try:
        ghi_chu = page.locator("textarea[placeholder*='Ghi chú'], textarea[placeholder*='ghi chú'], input[placeholder*='Gọi cho']").first
        if ghi_chu.count() > 0 and ghi_chu.is_visible(timeout=2000):
            ph = ghi_chu.get_attribute("placeholder")
            if ph:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (placeholder='{ph}')")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", "Không có placeholder tại Ghi chú")
                print(f"  [Row {row}] ❌ Fail")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy field Ghi chú — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 92 - Nhập > 100 ký tự Ghi chú → truncate
    row = 92
    try:
        ghi_chu = page.locator("textarea[placeholder*='Ghi chú'], textarea[placeholder*='ghi chú'], textarea").first
        if ghi_chu.count() > 0 and ghi_chu.is_visible(timeout=2000):
            ghi_chu.fill("B" * 110); page.wait_for_timeout(500)
            val = ghi_chu.input_value()
            if len(val) <= 100:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (len={len(val)})")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Cho phép nhập {len(val)} ký tự (>100)")
                print(f"  [Row {row}] ❌ Fail - len={len(val)}")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy field Ghi chú — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

# ─── PTTT + THANH TOÁN TCs ────────────────────────────────────────────────────
def run_pttt_tt(page, ws, ev, checkout_url):
    """Row 126, 139, 140, 144, 149"""
    try:
        page.goto(checkout_url, wait_until="domcontentloaded", timeout=15000)
        page.wait_for_timeout(2000)
    except Exception as e:
        print(f"  [PTTT] ❌ Load checkout: {e}"); return

    # Row 126 - UI Block PTTT
    row = 126
    try:
        found = False
        for sel in ["[class*='payment'], text=Phương thức thanh toán, text=PTTT"]:
            if page.locator(sel).count() > 0:
                found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không tìm thấy Block Phương thức thanh toán")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 139 - Hyperlink điều khoản
    row = 139
    try:
        dieu_khoan = page.locator("a:has-text('điều khoản'), a:has-text('Điều khoản'), text=điều khoản").first
        if dieu_khoan.count() > 0 and dieu_khoan.is_visible(timeout=2000):
            dieu_khoan.click(); page.wait_for_timeout(2000)
            cur = page.url
            if cur != checkout_url:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass → {cur}")
                page.go_back(); page.wait_for_timeout(1500)
            else:
                # Maybe opened in new tab
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass (new tab)")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không tìm thấy hyperlink điều khoản")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 140 - Hiển thị đúng tên gói
    row = 140
    try:
        found = False
        # Look for product/package name in right summary block
        for sel in ["[class*='summary'] h3, [class*='summary'] h4, [class*='order'] h3,[class*='product-name'], [class*='package-name']"]:
            el = page.locator(sel).first
            if el.count() > 0 and el.is_visible(timeout=1000) and el.inner_text().strip():
                found = True; break
        if found:
            write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
        else:
            shot(page, ev, f"FAIL_TC_11.{row}")
            write_result(ws, row, "Fail", "Không hiển thị tên gói trong block Thông tin thanh toán")
            print(f"  [Row {row}] ❌ Fail")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 144 - Btn Áp dụng enable/disable theo mã KM
    row = 144
    try:
        khuyen_mai_input = page.locator("input[placeholder*='mã khuyến mãi'], input[placeholder*='Nhập mã']").first
        apply_btn = page.locator("button:has-text('Áp dụng')").first
        if khuyen_mai_input.count() > 0 and apply_btn.count() > 0:
            # Check disabled when empty
            khuyen_mai_input.fill("")
            page.wait_for_timeout(300)
            disabled_empty = apply_btn.get_attribute("disabled") is not None or \
                             "disabled" in (apply_btn.get_attribute("class") or "") or \
                             not apply_btn.is_enabled()
            # Type 1 char → check enabled
            khuyen_mai_input.fill("X"); page.wait_for_timeout(300)
            enabled_with_val = apply_btn.is_enabled()
            if disabled_empty and enabled_with_val:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"disabled_empty={disabled_empty}, enabled_val={enabled_with_val}")
                print(f"  [Row {row}] ❌ Fail")
            khuyen_mai_input.fill("")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy input mã KM hoặc btn Áp dụng — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

    # Row 149 - Click Thanh toán khi chưa điền đủ
    row = 149
    try:
        # Clear all fields first, then click Thanh toán
        thanh_toan_btn = page.locator("button:has-text('Thanh toán'), button:has-text('Tiếp tục')").first
        if thanh_toan_btn.count() > 0:
            # Make sure no required fields are filled
            name_f = find_name_field(page)
            phone_f = find_phone_field(page)
            if name_f: name_f.fill("")
            if phone_f: phone_f.fill("")
            page.wait_for_timeout(300)
            thanh_toan_btn.click(); page.wait_for_timeout(1000)
            # Check error messages
            err_count = page.locator("[class*='error'], [class*='invalid'], .ant-form-item-explain").count()
            if err_count > 0 and page.url == checkout_url:
                write_result(ws, row, "Pass"); print(f"  [Row {row}] ✅ Pass ({err_count} lỗi)")
            else:
                shot(page, ev, f"FAIL_TC_11.{row}")
                write_result(ws, row, "Fail", f"Không có lỗi validation hoặc đã chuyển trang, URL={page.url}")
                print(f"  [Row {row}] ❌ Fail")
        else:
            write_result(ws, row, "Manual", "Không tìm thấy btn Thanh toán — verify thủ công")
            print(f"  [Row {row}] 🟡 Manual")
    except Exception as e:
        write_result(ws, row, "Fail", str(e)[:60]); print(f"  [Row {row}] ❌ {e}")

# ─── MAIN ─────────────────────────────────────────────────────────────────────
def main():
    # Setup
    run_dir = os.path.join(RUN_ROOT, datetime.now().strftime("%Y-%m-%d_%H-%M"))
    ev_dir  = os.path.join(run_dir, "evidence", "screenshots")
    os.makedirs(ev_dir, exist_ok=True)
    print(f"\n{'='*60}")
    print(f"  VIBE TEST — Thông tin chung")
    print(f"  {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    print(f"  Evidence: {ev_dir}")
    print(f"{'='*60}\n")

    # Load workbook
    wb = openpyxl.load_workbook(TC_FILE)
    ws = wb.active

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=False, slow_mo=150)
        ctx     = browser.new_context(viewport={"width": 1440, "height": 900})
        page    = ctx.new_page()

        # Get fresh checkout URL
        print("[STEP 1] Setup checkout session...")
        checkout_url = go_checkout(page, PRODUCT_URL)
        if not checkout_url:
            print("❌ Không lấy được checkout URL. Dừng.")
            browser.close(); return

        # Run TC groups
        print("\n[STEP 2] Header TCs (Row 12-14)...")
        run_row12(page, ws, ev_dir, checkout_url)
        checkout_url = go_checkout(page, PRODUCT_URL)  # fresh URL after nav away
        if checkout_url:
            run_row13(page, ws, ev_dir, checkout_url)
            checkout_url = go_checkout(page, PRODUCT_URL)
        run_row14(page, ws, ev_dir)
        checkout_url = go_checkout(page, PRODUCT_URL)

        if checkout_url:
            print("\n[STEP 3] Block Sản phẩm (Row 20-24)...")
            run_sanpham(page, ws, ev_dir, checkout_url)

            print("\n[STEP 4] Block Họ tên (Row 27-34)...")
            checkout_url = go_checkout(page, PRODUCT_URL)
            run_hotên(page, ws, ev_dir, checkout_url)

            print("\n[STEP 5] Block Số điện thoại (Row 36-41)...")
            checkout_url = go_checkout(page, PRODUCT_URL)
            run_sdt(page, ws, ev_dir, checkout_url)

            print("\n[STEP 6] Block Email (Row 43-49)...")
            run_email(ws)

            print("\n[STEP 7] Block Địa chỉ (Row 52, 72, 73, 75, 77, 90, 92)...")
            checkout_url = go_checkout(page, PRODUCT_URL)
            run_diachi(page, ws, ev_dir, checkout_url)

            print("\n[STEP 8] PTTT + Thông tin thanh toán (Row 126, 139, 140, 144, 149)...")
            checkout_url = go_checkout(page, PRODUCT_URL)
            run_pttt_tt(page, ws, ev_dir, checkout_url)

        browser.close()

    # Save
    wb.save(TC_FILE)
    print(f"\n{'='*60}")
    print(f"  ✅ Hoàn tất! File đã lưu: {TC_FILE}")
    print(f"  Evidence tại: {ev_dir}")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
